--Bắt đầu chạy
CREATE DATABASE NHOM3_QLNS
GO
USE NHOM3_QLNS
GO
CREATE TABLE SO_CMND(
	CMND VARCHAR(12) PRIMARY KEY,
	NGAY_CAP DATETIME,
	NOI_CAP NVARCHAR(30)
)
GO
CREATE TABLE DAN_TOC(
	MADT SMALLINT PRIMARY KEY IDENTITY,
	TEN_DT NVARCHAR(30),
	PHU_CAP DECIMAL(10,0)
)
GO
CREATE TABLE TON_GIAO(
	MATG SMALLINT PRIMARY KEY IDENTITY,
	TEN_TG NVARCHAR(30)
)
GO
CREATE TABLE HOC_VAN
(
	MAHV TINYINT PRIMARY KEY IDENTITY,
	TENHV NVARCHAR(30),
	CHUYEN_NGANH NVARCHAR(100)
)
GO
CREATE TABLE HO_SO
(
	MAHS VARCHAR(10) PRIMARY KEY,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	GIOI_TINH BIT,
	NGAY_SINH DATETIME,
	NOI_SINH NVARCHAR(30),
	HO_KHAU NVARCHAR(200),
	DC_LIEN_HE NVARCHAR(200),
	CMND VARCHAR(12) FOREIGN KEY REFERENCES SO_CMND(CMND),
	DANTOC SMALLINT FOREIGN KEY REFERENCES DAN_TOC(MADT),
	TONGIAO SMALLINT FOREIGN KEY REFERENCES TON_GIAO(MATG),
	SO_DT VARCHAR(15),
	EMAIL VARCHAR(50),
	NGOAI_NGU NVARCHAR(50),
	TRINH_DO_HV TINYINT FOREIGN KEY REFERENCES HOC_VAN(MAHV),
	GHI_CHU NVARCHAR(100)
)
GO
CREATE TABLE QUAN_HE_GIA_DINH
(
	MAQHGD INT PRIMARY KEY IDENTITY,
	MAHS VARCHAR(10) FOREIGN KEY REFERENCES HO_SO(MAHS),
	HOTEN NVARCHAR(50),
	QUAN_HE NVARCHAR(10),
	NAM_SINH VARCHAR(4),
	NGHE_NGHIEP NVARCHAR(50),
	GIOI_TINH BIT
)
GO
CREATE TABLE PHONG_BAN
(
	MAPB VARCHAR(10) PRIMARY KEY,
	TEN_PB NVARCHAR(50)
)
GO
CREATE TABLE CHUC_VU
(
	MACV VARCHAR(10) PRIMARY KEY,
	TEN_CV NVARCHAR(50),
	PHU_CAP DECIMAL(10,0)
)
GO
CREATE TABLE LUONG(
	BACLUONG SMALLINT PRIMARY KEY IDENTITY,
	LUONG_CO_BAN DECIMAL(10,0)
)
GO
CREATE TABLE NHAN_VIEN
(
	MANV VARCHAR(10) PRIMARY KEY,
	MAHS VARCHAR(10) FOREIGN KEY REFERENCES HO_SO(MAHS),
	NGAY_VAO_LAM DATETIME,
	TINH_TRANG TINYINT,
	MAT_KHAU VARCHAR(50),
	LOAI_NV TINYINT,
	LA_ADMIN BIT,
	PHONG VARCHAR(10) FOREIGN KEY REFERENCES PHONG_BAN(MAPB),
	CHUCVU VARCHAR(10) FOREIGN KEY REFERENCES CHUC_VU(MACV),
	BAC_LUONG SMALLINT FOREIGN KEY REFERENCES LUONG(BACLUONG)
)
GO
INSERT INTO SO_CMND VALUES('272483863','2011/9/21',N'Đồng Nai')
Go
INSERT INTO SO_CMND VALUES('','2011/9/21','')
go
INSERT INTO DAN_TOC VALUES(N'Kinh',0)
GO
INSERT INTO DAN_TOC VALUES(N'Mường',0)
GO
INSERT INTO TON_GIAO VALUES(N'Phật Giáo')
GO
INSERT INTO TON_GIAO VALUES(N'Thiên Chúa')
GO
INSERT INTO HOC_VAN VALUES(N'Đại Học','CNTT')
GO
INSERT INTO HOC_VAN VALUES(N'Cao Đẳng','CNTT')
GO
INSERT INTO LUONG VALUES(3000000)
GO
INSERT INTO LUONG VALUES(4000000)
GO
INSERT INTO CHUC_VU VALUES('QLPM',N'Quản Lý Phần Mềm Công Ty',0)
GO
INSERT INTO CHUC_VU VALUES('TPIT',N'Trưởng Phòng IT',100000)
GO
INSERT INTO PHONG_BAN VALUES('IT','IT')
GO
INSERT INTO HO_SO VALUES('HS00001',N'Trần Văn',N'Thỏa',1,'1994/2/10',N'Đồng Nai',N'Đồng Nai',N'Lớp 15DTH1LT2 Trường DNTU','272483863',1,1,'0168 653 9737','thoa.tranvan@uni.dntu.edu.vn',N'Tiếng Anh',1,'')
GO
INSERT INTO HO_SO VALUES('HS00002',N'Huỳnh Hoàng',N'Quân',1,'1992/5/3',N'Đồng Nai',N'Đồng Nai',N'Lớp 15DTH1LT2 Trường DNTU','',1,1,'0964 443 332','quan.huynhhoang@uni.dntu.edu.vn',N'Tiếng Anh',1,'')
GO
INSERT INTO NHAN_VIEN VALUES('NV01','HS00001','2015/10/1',1,'123456',1,1,'IT','TPIT',1)
GO
INSERT INTO NHAN_VIEN VALUES('NV02','HS00002','2015/10/1',1,'123456',1,1,'IT','QLPM',1)
go
INSERT INTO QUAN_HE_GIA_DINH VALUES('HS00002',N'Văn A','Cha','1964','',1)
GO
CREATE PROC SpLogin
(
	@MANV VARCHAR(10),
	@MATKHAU VARCHAR(50)	
)
AS
SELECT NHAN_VIEN.MANV,HO_SO.HO,HO_SO.TEN,NHAN_VIEN.LA_ADMIN FROM NHAN_VIEN
INNER JOIN HO_SO ON NHAN_VIEN.MAHS=HO_SO.MAHS
WHERE NHAN_VIEN.MANV=@MANV AND NHAN_VIEN.MAT_KHAU=@MATKHAU
GO
CREATE PROC TESTCONNECTION
AS
BEGIN
	declare @result bit
	set @result=0
	IF object_id('NHAN_VIEN') is not null
		if object_id('CHUC_VU') is not null
		if object_id('DAN_TOC') is not null
		if object_id('HO_SO') is not null
		if object_id('LUONG') is not null
		if object_id('HOC_VAN') is not null
		if object_id('PHONG_BAN') is not null
		if object_id('QUAN_HE_GIA_DINH') is not null
		if object_id('SO_CMND') is not null
		if object_id('TON_GIAO') is not null
		set @result=1
	select @result
END
GO
CREATE PROC InsertDanToc
(
	@TEN_DT NVARCHAR(30),
	@PHU_CAP DECIMAL(10,0)
)
AS
BEGIN
	
	INSERT INTO DAN_TOC VALUES(@TEN_DT,@PHU_CAP)
	
	SELECT @@IDENTITY
END
GO
CREATE PROC InsertTonGiao
(
	@TEN_TG NVARCHAR(30)
)
AS
BEGIN
	
	INSERT INTO TON_GIAO VALUES(@TEN_TG)
	
	SELECT @@IDENTITY
END
GO
CREATE PROC InsertLuong(
	@LUONG_CO_BAN decimal(10,0)
)
as
begin
	INSERT INTO LUONG VALUES(@LUONG_CO_BAN)
	
	SELECT @@IDENTITY
end
GO
CREATE PROC InsertHocVan(
	@TENHV nvarchar(30),
	@CHUYEN_NGANH nvarchar(100)
)
as
begin
	INSERT INTO HOC_VAN VALUES(@TENHV,@CHUYEN_NGANH)
	
	SELECT @@IDENTITY
end
GO
CREATE PROC InsertThanNhan(
	@MAHS varchar(10),
	@HOTEN nvarchar(50),
	@QUAN_HE nvarchar(10),
	@NAM_SINH varchar(4),
	@NGHE_NGHIEP nvarchar(50),
	@GIOI_TINH bit
)
as
begin
	INSERT INTO QUAN_HE_GIA_DINH VALUES(@MAHS,@HOTEN,@QUAN_HE,@NAM_SINH,@NGHE_NGHIEP,@GIOI_TINH)
	
	SELECT @@IDENTITY
end
go
create proc EditCMND(
	@CMNDCU varchar(12),
	@CMND varchar(12),
	@NGAY_CAP datetime,
	@NOI_CAP nvarchar(30),
	@MaHS varchar(10)
)
as
begin
update HO_SO set CMND='' where MAHS=@MaHS
if @CMNDCU<>''
begin
update SO_CMND set CMND=@CMND, NGAY_CAP=@NGAY_CAP,NOI_CAP=@NOI_CAP where CMND=@CMNDCU
end
else
begin
	insert into SO_CMND values(@CMND,@NGAY_CAP,@NOI_CAP)
end
update HO_SO set CMND=@CMND where MAHS=@MaHS

end
go
create proc InsertHoSoNV(
	@HO nvarchar(30),
	@TEN nvarchar(10),
	@GIOI_TINH bit,
	@NGAY_SINH datetime,
	@NOI_SINH nvarchar(30),
	@HO_KHAU nvarchar(200),
	@DC_LIEN_HE nvarchar(200),
	@CMND varchar(12),
	@DANTOC smallint,
	@TONGIAO smallint,
	@SO_DT varchar(15),
	@EMAIL varchar(50),
	@NGOAI_NGU nvarchar(50),
	@TRINH_DO_HV tinyint,
	@GHI_CHU nvarchar(100),
	@MANV varchar(10),
	@NGAY_VAO_LAM datetime,
	@TINH_TRANG tinyint,
	@LOAI_NV tinyint,
	@LA_ADMIN bit,
	@PHONG varchar(10),
	@CHUCVU varchar(10),
	@BAC_LUONG smallint
)
as
begin
	declare @MAHS varchar(10)
	set @MAHS=(SELECT MAX(MAHS) FROM HO_SO)
	
	DECLARE @SOHS INT
	SET @SOHS=CAST(SUBSTRING(@MAHS,3,LEN(@MAHS)) AS INT)+1
	
	IF @SOHS<10
	SET @MAHS='HS0000'+CAST(@SOHS AS CHAR(1))
	ELSE
	IF @SOHS<100
	SET @MAHS='HS000'+CAST(@SOHS AS CHAR(2))
	ELSE
	IF @SOHS<1000
	SET @MAHS='HS00'+CAST(@SOHS AS CHAR(3))
	ELSE
	IF @SOHS<10000
	SET @MAHS='HS0'+CAST(@SOHS AS CHAR(4))
	ELSE
	SET @MAHS='HS'+CAST(@SOHS AS VARCHAR(8))
	
	INSERT INTO HO_SO VALUES(@MAHS,@HO,@TEN,@GIOI_TINH,@NGAY_SINH,@NOI_SINH,@HO_KHAU,@DC_LIEN_HE,@CMND,@DANTOC,@TONGIAO,@SO_DT,@EMAIL,@NGOAI_NGU,@TRINH_DO_HV,@GHI_CHU)
	
	INSERT INTO NHAN_VIEN VALUES(@MANV,@MAHS,@NGAY_VAO_LAM,@TINH_TRANG,'123456',@LOAI_NV,@LA_ADMIN,@PHONG,@CHUCVU,@BAC_LUONG)
	
	SELECT @MAHS
	
end
go
create proc UpdateNV(
	@HO nvarchar(30),
	@TEN nvarchar(10),
	@GIOI_TINH bit,
	@NGAY_SINH datetime,
	@NOI_SINH nvarchar(30),
	@HO_KHAU nvarchar(200),
	@DC_LIEN_HE nvarchar(200),
	@DANTOC smallint,
	@TONGIAO smallint,
	@SO_DT varchar(15),
	@EMAIL varchar(50),
	@NGOAI_NGU nvarchar(50),
	@TRINH_DO_HV tinyint,
	@GHI_CHU nvarchar(100),
	@MANV varchar(10),
	@NGAY_VAO_LAM datetime,
	@TINH_TRANG tinyint,
	@LOAI_NV tinyint,
	@LA_ADMIN bit,
	@PHONG varchar(10),
	@CHUCVU varchar(10),
	@BAC_LUONG smallint,
	@MAHS varchar(10)
)
as
begin
	
	update HO_SO set HO=@HO,TEN=@TEN,GIOI_TINH=@GIOI_TINH,NGAY_SINH=@NGAY_SINH,NOI_SINH=@NOI_SINH,HO_KHAU=@HO_KHAU,
	DC_LIEN_HE=@DC_LIEN_HE,DANTOC=@DANTOC,TONGIAO=@TONGIAO,SO_DT=@SO_DT,EMAIL=@EMAIL,NGOAI_NGU=@NGOAI_NGU,
	TRINH_DO_HV=@TRINH_DO_HV,GHI_CHU=@GHI_CHU WHERE MAHS=@MAHS
	
	UPDATE NHAN_VIEN SET NGAY_VAO_LAM=@NGAY_VAO_LAM,@TINH_TRANG=@TINH_TRANG,LOAI_NV=@LOAI_NV,LA_ADMIN=@LA_ADMIN,
	PHONG=@PHONG,CHUCVU=@CHUCVU,BAC_LUONG=@BAC_LUONG WHERE MANV=@MANV
end
GO
CREATE TRIGGER KT_THAN_NHAN ON QUAN_HE_GIA_DINH
FOR UPDATE,INSERT
AS
BEGIN
	IF UPDATE(HOTEN)
	BEGIN
		IF EXISTS(SELECT QHGD.MAQHGD FROM QUAN_HE_GIA_DINH QHGD INNER JOIN inserted INS ON QHGD.MAHS=INS.MAHS AND QHGD.HOTEN=INS.HOTEN AND QHGD.QUAN_HE=INS.QUAN_HE WHERE QHGD.MAQHGD<>INS.MAQHGD)
		BEGIN
			ROLLBACK TRAN
		END
	END
END